openapi: 3.0.3
info:
  title: Swagger repository checker - OpenAPI 3.0
  description: |-
    TUI coding test API
  termsOfService: http://swagger.io/terms/
  contact:
    email: pawel.domanski@endava.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://test.swagger.io/api/v3
tags:
  - name: repo
    description: Everything about user repo list
    externalDocs:
      description: Find out more
      url: http://swagger.io

paths:
  /repository/{username}/:
    get:
      tags:
        - repo
      summary: Get list of customer repositories
      description: List of parsed repositories which are not forks from github
      operationId: list
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: Login from github
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
        '400':
          description: Invalid ID supplied
        '404':
          description: Repository not found
        '405':
          description: Validation exception
        '406':
          description: Incorrect header
components:
  schemas:
    Branch:
      type: object
      properties:
        name:
          type: string
          example: pdomanskiendava
        lastCommit:
          type: string
          example: pdomanskiendava
    Repository:
      type: object
      properties:
        name:
          type: string
          example: pdomanskiendava
        owner:
          type: string
          example: pdomanskiendava
        lastCommit:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
    Error:
      type: object
      properties:
        code:
          type: string
          example: 406
        message:
          type: string
          example: asd